/**
 * 圣遗物主词条表
 */
export const ArtifactParamTypes = [
    'CRIT Rate',
    'CRIT DMG',
    'ATK',
    'Elemental Mastery',
    'Energy Recharge',
    'HP',
    'DEF',
    'Physical DMG Bonus',
    'Healing Bonus',
    'Geo DMG Bonus',
    'Anemo DMG Bonus',
    'Cryo DMG Bonus',
    'Hydro DMG Bonus',
    'Pyro DMG Bonus',
    'Electro DMG Bonus',
]
/**
 * 圣遗物副词条表
 */
export const ArtifactSubParamTypes = [
    'CRIT Rate',
    'CRIT DMG',
    'ATK',
    'Elemental Mastery',
    'Energy Recharge',
    'HP',
    'DEF',
    'Physical DMG',
    'Healing Bonus',
]
/**
 * 圣遗物名表
 */
export const ArtifactNames = [

    "Initiate's Flower",
    "Initiate's Feather",
    "Adventurer's Flower",
    "Adventurer's Tail Feather",
    "Adventurer's Pocket Watch",
    "Adventurer's Golden Goblet",
    "Adventurer's Bandana",
    "Lucky Dog's Clover",
    "Lucky Dog's Eagle Feather",
    "Lucky Dog's Hourglass",
    "Lucky Dog's Goblet",
    "Lucky Dog's Silver Circlet",
    "Traveling Doctor's Silver Lotus",
    "Traveling Doctor's Owl Feather",
    "Traveling Doctor's Pocket Watch",
    "Traveling Doctor's Medicine Pot",
    "Traveling Doctor's Handkerchief",
    'Heart of Comradeship',
    'Feather of Homecoming',
    'Sundial of the Sojourner',
    'Goblet of the Sojourner',
    'Crown of Parting',
    "Tiny Miracle's Flower",
    "Tiny Miracle's Feather",
    "Tiny Miracle's Hourglass",
    "Tiny Miracle's Goblet",
    "Tiny Miracle's Earrings",
    "Berserker's Rose",
    "Berserker's Indigo Feather",
    "Berserker's Timepiece",
    "Berserker's Bone Goblet",
    "Berserker's Battle Mask",
    "Instructor's Brooch",
    "Instructor's Feather Accessory",
    "Instructor's Pocket Watch",
    "Instructor's Tea Cup",
    "Instructor's Cap",
    "Exile's Flower",
    "Exile's Feather",
    "Exile's Pocket Watch",
    "Exile's Goblet",
    "Exile's Circlet",
    "Guardian's Flower",
    "Guardian's Sigil",
    "Guardian's Clock",
    "Guardian's Vessel",
    "Guardian's Band",
    'Medal of the Brave',
    'Prospect of the Brave',
    'Fortitude of the Brave',
    'Outset of the Brave',
    'Crown of the Brave',
    "Martial Artist's Red Flower",
    "Martial Artist's Feather Accessory",
    "Martial Artist's Water Hourglass",
    "Martial Artist's Wine Cup",
    "Martial Artist's Bandana",
    "Gambler's Brooch",
    "Gambler's Feather Accessory",
    "Gambler's Pocket Watch",
    "Gambler's Dice Cup",
    "Gambler's Earrings",
    "Scholar's Bookmark",
    "Scholar's Quill Pen",
    "Scholar's Clock",
    "Scholar's Ink Cup",
    "Scholar's Lens",
    'Tiara of Flame',
    'Tiara of Torrents',
    'Tiara of Thunder',
    'Tiara of Frost',
    "Gladiator's Nostalgia",
    "Gladiator's Destiny",
    "Gladiator's Longing",
    "Gladiator's Intoxication",
    "Gladiator's Triumphus",
    "Troupe's Dawnlight",
    "Bard's Arrow Feather",
    "Concert's Final Hour",
    "Wanderer's String Kettle",
    "Conductor's Top Hat",
    "Thundersoother's Heart",
    "Thundersoother's Plume",
    'Hour of Soothing Thunder',
    "Thundersoother's Goblet",
    "Thundersoother's Diadem",
    "Thunderbird's Mercy",
    'Survivor of Catastrophe',
    'Hourglass of Thunder',
    'Omen of Thunderstorm',
    "Thunder Summoner's Crown",
    "Maiden's Distant Love",
    "Maiden's Heart-stricken Infatuation",
    "Maiden's Passing Youth",
    "Maiden's Fleeting Leisure",
    "Maiden's Fading Beauty",
    'In Remembrance of Viridescent Fields',
    'Viridescent Arrow Feather',
    "Viridescent Venerer's Determination",
    "Viridescent Venerer's Vessel",
    "Viridescent Venerer's Diadem",
    "Witch's Flower of Blaze",
    "Witch's Ever-Burning Plume",
    "Witch's End Time",
    "Witch's Heart Flames",
    "Witch's Scorching Hat",
    "Lavawalker's Resolution",
    "Lavawalker's Salvation",
    "Lavawalker's Torment",
    "Lavawalker's Epiphany",
    "Lavawalker's Wisdom",
    'Royal Flora',
    'Royal Plume',
    'Royal Pocket Watch',
    'Royal Silver Urn',
    'Royal Masque',
    'Bloodstained Flower of Iron',
    'Bloodstained Black Plume',
    'Bloodstained Final Hour',
    "Bloodstained Chevalier's Goblet",
    'Bloodstained Iron Mask',
    'Flower of Creviced Cliff',
    'Feather of Jagged Peaks',
    'Sundial of Enduring Jade',
    'Goblet of Chiseled Crag',
    'Mask of Solitude Basalt',
    "Summer Night's Bloom",
    "Summer Night's Finale",
    "Summer Night's Moment",
    "Summer Night's Waterballoon",
    "Summer Night's Mask",
    'Snowswept Memory',
    "Icebreaker's Resolve",
    "Frozen Homeland's Demise",
    'Frost-Weaved Dignity',
    "Broken Rime's Echo",
    'Gilded Corsage',
    'Gust of Nostalgia',
    'Copper Compass',
    'Goblet of Thundering Deep',
    'Wine-Stained Tricorne',
    'Flower of Accolades',
    'Ceremonial War-Plume',
    'Orichalceous Time-Dial',
    "Noble's Pledging Vessel",
    "General's Ancient Helm",
    'Stainless Bloom',
    "Wise Doctor's Pinion",
    'Moment of Cessation',
    'Surpassing Cup',
    'Mocking Mask',
]
/**
 *  Artifacts user
 */
export const ArtifactUsers = [
    '空已装备',
    '荧已装备',
    '安柏已装备',
    '凯亚已装备',
    '丽莎已装备',
    '琴已装备',
    '可莉已装备',
    '诺艾尔已装备',
    '芭芭拉已装备',
    '温迪已装备',
    '雷泽已装备',
    '迪卢克已装备',
    '班尼特已装备',
    '菲谢尔已装备',
    '北斗已装备',
    '凝光已装备',
    '香菱已装备',
    '行秋已装备',
    '重云已装备',
    '砂糖已装备',
    '莫娜已装备',
    '刻晴已装备',
    '七七已装备',
    '达达利亚已装备',
    '迪奥娜已装备',
    '钟离已装备',
    '辛焱已装备',
    '阿贝多已装备',
    '甘雨已装备',
    '魈已装备',
    '胡桃已装备',
    '罗莎莉亚已装备',
]
